### ISSUE TITLE
New tool: PyBoolNet

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#13]

**Comment by aurelien-naldi** [comment]
PyBoolNet (see https://github.com/hklarner/PyBoolNet) is a python tool, but it comes with internal copies of it's binary dependencies. To integrate it, we need to package these dependencies properly and adapt PyBoolNet to use the shared ones.

Dependencies:
- [x] potassco (gringo, clasp)
- [ ] NuSMV-a: https://github.com/hklarner/NuSMV-a
- [ ] BNetToPrime: https://github.com/xstreck1/BNetToPrime
- [ ] eqntott: https://github.com/TheProjecter/eqntott
- [ ] espresso: https://courses.cs.washington.edu/courses/cse467/98au/espresso/espresso.html

Other tasks:
- [ ] Use shared binaries in PyBoolNet
- [ ] Example notebook

@hklarner: do you still have some time for this?

**Comment by hklarner** [comment]
I am not sure I can help. How can I help? What should I do?

**Comment by aurelien-naldi** [comment]
Hi Hannes,

you obviously know PyBoolNet better than anyone else, so I'm sure you can help, at least by telling us where to look! I can prepare the conda packages for all dependencies, but I'm not sure what is needed to let PyBoolNet use them instead of using the internal copy.

* Do you want to keep these inner copies for use outside of conda? The easy solution would be to fully remove them, but this would probably break the workflows of your current users. It may be better to add a packaging option. At runtime, you can then detect if this folder exists and add it to the execution PATH.
* Grepping through your code, it seems to explicitly call using a local path. Once the local folder has been added to the PATH, you can use regular command calls.
* I think you had problems at some point with a potassco update, it looks like they didn't add any breaking change since, did you try to use a newer gringo/clasp/clingo ? If not, do you think running your test suite with a newer version would be enough to catch most issues?

**Comment by aurelien-naldi** [comment]
I added packages for BNetToPrime and eqntott, these ones were easy.

For NuSMV-a: I had to fix bogus patches (I can send a pull request) and fight a bit with conda-build but it is now working. As it gives a NuSMV binary, I think I will replace our NuSMV package with this (it adds an extra command line switch and should behave exactly as the original one otherwise).

Espresso builds fine on my system, but not in conda-build, I may end up adding the binary instead of building from source.

**Comment by pauleve** [comment]
Great! I would keep the official nusmv alongside.

**Comment by pauleve** [comment]
Also we should probably wait for networkx 2.4 compatibility raised in https://github.com/jcrozum/StableMotifs/issues/12 to avoid forcing a downgrade in the Docker image (looks like the fix is quite easy).

**Comment by aurelien-naldi** [comment]
I am adding a find_command() function in PyBoolNet.Utility.Misc and using it instead of parsing the configuration everywhere. With this change, we should be able to remove the included binaries from the conda package and replace the settings.cfg file to use the shared commands. The normal version still uses the internal ones.

A few issues remain:
* My new eqntott binary seems to make PyBoolNet tests fail (it works if I use the provided one)
* Some tests fail because graphviz packages in conda does not support jpeg and gif formats
* A few other tests fail, I'm not sure why yet

I will do some changes in a temporary fork of PyBoolNet, we can then see how to integrate them

**Comment by aurelien-naldi** [comment]
All other test failures were related to networkx, which was indeed easy to fix.
All fixes should be in PR hklarner/PyBoolNet#35

**Comment by aurelien-naldi** [comment]
Hannes has integrated the previous PR a while ago (thanks!). I should be able to work again on it at the end of the month.

Left to do:

- [ ] fix eqntott package
- [ ] prepare the conda package for pyboolnet itself (mostly removing the private copy of dependencies after install)
- [ ] Add a couple of demo notebooks (the existing examples should make a good starting point)

@hklarner : I can add the conda recipe to https://github.com/colomoto/colomoto-conda or propose it for integration in the main pyboolnet repository, whatever is best for you.

**Comment by aurelien-naldi** [comment]
Since the last comment, I uploaded a conda package for eqntott based on the binary provided with PyBoolNet. It works but I'm not fond of this solution.

@hklarner: do you have some kind of official source for eqntott source or binary?

I also added a basic tutorial and to_pyboolnet function in ginsim and biolqm packages. Loic is planning to add the method to minibn as well.

Beside the fact that the eqntott package is not so clean, I think we can close this issue.

**Comment by hklarner** [comment]
I think we took it from here
 * https://code.google.com/archive/p/eqntott/

not sure this helps.

Can you post a link to the function `to_pyboolnet`? Curious.

**Comment by aurelien-naldi** [comment]
Thanks for the link, I was using another "modernized" version, I'll check if this one works better.

The to_pyboolnet function is fairly simple and similar to other conversions functions: export the model in bnet format in a temporary file, and use PyBoolNet API to load this file. The code is here: https://github.com/GINsim/GINsim-python/blob/master/biolqm/__init__.py

**Comment by aurelien-naldi** [comment]
It seems to work fine with this source version, I updated the recipe and uploaded a new version of the conda package

**Comment by pauleve** [comment]
I added the shortcut in `minibn`: https://github.com/colomoto/colomoto-jupyter/commit/a086df0b2d13a9600e4dfe46c0b26eebb66bee1e
