### ISSUE TITLE
clingo: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#21]
Running clingo in the docker results in
```
clingo: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```
maybe a bug in the conda distribution? (note that there already exists a conda package mentioned here : https://sourceforge.net/p/potassco/mailman/message/35257803/?SetFreedomCookie , maybe a source of inspiration to fix it)

**Comment by aurelien-naldi** [comment]
The problem is in the conda package. For this build, I didn't try to include the python module but I let cmake detect python, so it used python 2.7 from my system. This can be fixed easily by disabling the python module explicitly.

To include the python module, we need to add python as a build and run dependency, and to copy the python module in the package. It should not require many changes to the build script but the package would probably have to target a specific python version.

In GINsim, we don't need the python module, what about pypint?
Even if we don't directly need it yet, I it makes sense to include it, I'm finishing a new version of the package with it.

**Comment by pauleve** [comment]
Pint does not rely on the python module (yet, it is actually planned..), but other tools that may be good candidates for inclusion do (like caspo/caspots for Boolean network identification). I guess for M1 it is fine not having it, but it should be fixed at some point. The conda package of clingo here : https://github.com/svidela/clingo-conda/tree/master/clingo seems to support it.

**Comment by aurelien-naldi** [comment]
I looked at this package but it is for an older clingo version (5.0 instead of 5.2) and they moved from scons to cmake in the meantime. While writing the previous message, I was trying to build a new package with the module. It works in conda and the new package is online. It also works in my local docker build, I'll push a change to the dockerfile to rebuild the online image

**Comment by pauleve** [comment]
Great! Speaking of updating the Dockerimage, it would be better to have the explicit list of packages and their version to install, so when we update a package, we increase the version and it is automatically rebuilt..

**Comment by aurelien-naldi** [comment]
Yes, it would be cleaner like that indeed. I will start adding exact version requirements in the colomoto conda metapackage, then the Dockerfile can specify the version of this package.

**Comment by pauleve** [comment]
I would be more in favour to have the explicit list in the Dockerfile itself, otherwise it means that as soon as someone updates its software/python library,  you have to update the conda package before the docker can be updated... and we need to make this process easy. Moreover, it makes very difficult to know what is in the docker.

**Comment by aurelien-naldi** [comment]
We can have both, but we need it in conda anyway and I see little gain in maintaining the full list of versions twice. The docker includes the conda packages, thus it has to wait for them anyway ;)

To know what is in the docker, we can look at the colomoto metapackage. We will never be perfectly sure about the exact content for some of the dependencies (but we can look at the list of conda packages).

I opened issue  #22 to discuss this
