### ISSUE TITLE
Editing the Ginsim/NuSMV model

### ISSUE THREAD

**Issue by xhajnal** [colomoto/colomoto-docker#34]
Please, is there an example, documentation, or code for editing the model itself? (value and condition of the edge) Either in GinSim model or after importing to NuSMV?

**Comment by pauleve** [comment]
@aurelien-naldi is it possible with current GINsim/bioLQM API?

**Comment by aurelien-naldi** [comment]
Could you explain further what you would like to do? Edges have only a threshold value in GINsim, which can be changed only if the source node is multi-valued. They have no condition: everything lies in the logical rules associated to the nodes, which is the part you probably want to edit. It should be possible to change everything from the python bindings, but no specific work has been done to make this convenient. We are planning some changes in the data structure and API, which should facilitate programmatic model edition.

**Comment by xhajnal** [comment]
Actually, both of them (the thresholds of an entity value when is the edge active (called "Min","Max" in GINsim GUI) and the function joining multiple incoming edges). Also, the value up to which is the entity regulated (called "value") can be edited, but I do not need to edit now. 

How may I help you with the process?

**Comment by pauleve** [comment]
We just implemented a simple Python API to create and modify Boolean and multivalued models.
There is a brief tutorial here:
https://nbviewer.jupyter.org/github/colomoto/colomoto-docker/blob/master/tutorials/Model%20creation%20and%20edition%20with%20minibn.ipynb
it notably shows the rewriting of multi-valued networks and import of existing models from bioLQM.

You can give a try using the `next` version (`colomoto-docker -V next`), which will be tagged soon.
Let us know if it fills your needs.

**Comment by xhajnal** [comment]
1.  I did not catch how to encode negative regulation in multivalued networks ( f.e. x-|y by means of y rises from 0 to 1 if x <2 ). 
2.  The multiple conversion is pitty (editor -> biolqm -> ginsim -> nusmv).

Besides these 2 it works perfectly, thank you a lot.

Now I only need to import the state space (from ginsim) into some tool for parameter synthesis. Do you have any trick?

**Comment by aurelien-naldi** [comment]
For your first question, in the textual representation, you can use "!" do denote a negation, and ":" to use a threshold other than 1. a:2 means a>=2, !a:2 means a<2
In the python syntax, the negation is a ~, and the threshold a /, otherwise it should be similar.

For your second comment, minibn has been added in the last days, we will probably add a direct conversion from minibn to ginsim in the future, but we can't add a hand-coded method for every possible conversion. With more metadata we could imagine constructing a "conversion path" automatically, but it is beyond our current scope.

For the last part, I'm not sure what you want to achieve. By state space, do you mean the full state transition graph with all possible states and existing transitions? We can compute it for small models, but it is in a java data-structure and may need some work to be used in python in a convenient way.

**Comment by pauleve** [comment]
I python you can encode it by doing:
```
x,y = mvf.vars("x","y")
mvf[y] = ~(x/2)
 # or equivalently
mvf[y] = (x<2)
```

**Comment by pauleve** [comment]
For the time evaluation, you can use the`%time` macro in jupyter, e.g., 
```
smv = ginsim.to_nusmv(biolqm.to_ginsim(mvf.to_biolqm()))
.. add properties..
%time smv.verify()
```
and/or the `time` python module, to cumulate several execution time.

I close the issue as your other concern is more related to features around the model-checking (I would guess a more efficient way is to custom a smv model to introduce variables for the different conditions and do a single NuSMV run).

**Comment by pauleve** [comment]
FYI, the image with persistent tag `2018-08-14` now contains the minibn module.
